version: 2
jobs:
  build:
    working_directory: ~/Wolox/redux-recompose
    parallelism: 1
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          shell: /bin/sh
          command: npm run test
